### ISSUE TITLE
Monthly carry over

### ISSUE THREAD

**Issue by AkshayM21** [19RyanA/CheckPCR#16] opened 2018-04-01 19:00 UTC
Before, as a new month began, CheckPCR would rollover past assignments and user generated tasks in the list view. However, it does not do that anymore. Moreover, one can't go back to view assignments due in previous months (using the left arrow button in the list view), whereas that was possible previously. Is this due to a new update or PCR itself?

**Comment by rianadon** [comment] 2018-04-02 03:42
Hi Akshay!

Thanks for creating the issue!

PCR has not changed recently as far as I know. If it did there'd probably be a lot more broken than just when things show up. And the extension hasn't been updated for more than a year now (let's call it "stability").

As for stuff rolling over, that currently is working for me. Are you on month or week view? Things were in a bit of a limbo yesterday since PCR was displaying April as the month and Check PCR was displaying March as the month, so only about 4 assignments were displayed for me, so maybe that led to some of your issues. Try refreshing if you haven't already.

And viewing assignments due in previous months should've never worked. If you go back a month in list view theoretically nothing should ever show up. I should really add some kind of message for that or implement loading previous / following months, but right now I'm busy trying to organize the codebase and make it less of a huge mess.

**Comment by AkshayM21** [comment] 2018-04-02 03:58
Hi Ryan,

Currently, assignments due in April now show up, but user-generated assignments do not (I did not specify a "due date" so they're technically due in "forever"). Are these supposed to roll over too? This happens in both week and month view.

**Comment by rianadon** [comment] 2018-04-02 04:04
Oh that's a bug! And I can reproduce that! Those are supposed to roll over too.
I've noticed in the process of organizing the codebase that I handle the cases of assignments due "forever" very terribly (I try to cast that string to a number a lot). Once I finish that up I'll take make sure these kind of assignments roll over.

Thanks!

**Comment by rianadon** [comment] 2018-10-10 17:55
This should be fixed with the code refactoring.

**Closed as completed by rianadon** 2018-10-10 17:55 UTC
